<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <!-- Основные настройки -->
  <TargetFrameworks>net9.0</TargetFrameworks>
  
  <OutputType>WinExe</OutputType>
  

  <!-- dotnet publish TNU.Desktop/TNU.Desktop.csproj -c Release -f net9.0 -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -->
  <!-- Windows настройки -->
  
 <TargetFramework Condition="'$(Configuration)' == 'Release'">net9.0</TargetFramework>
  <RuntimeIdentifier Condition="'$(Configuration)' == 'Release'">win-x64</RuntimeIdentifier>
  
  <OutputType>WinExe</OutputType>
  <SelfContained Condition="'$(Configuration)' == 'Release'">true</SelfContained>
  <PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
  <IncludeNativeLibrariesForSelfExtract Condition="'$(Configuration)' == 'Release'">true</IncludeNativeLibrariesForSelfExtract>
  <UseAppHost Condition="'$(Configuration)' == 'Release'">true</UseAppHost>

</PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../TNU.Core/TNU.Core.csproj" />
    </ItemGroup>
</Project>